default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
development:
  adapter: postgresql
  database: projblog_dev
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: projblog_test
  pool: 5
  timeout: 5000
production:
  adapter: postgresql
  database: projblog_prod
  pool: 5
  timeout: 5000
